spring:
  profiles:
    active: local

server:
  port: 8080

---
spring:
  profiles: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/crawler?serverTimezone=Asia/Seoul&useSSL=false
    username: cmuser
    password: qwer1234!
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.web: TRACE

